package:
  name: foyer
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python

  run:
    - python
    - parmed
    - mbuild >=0.6.1
    - networkx
    - oset
    - six
    - openmm
    - plyplus

test:
  requires:
    - pytest >=3.0

  source_files:
    - foyer/forcefields/*
    - foyer/opls_validation/*
    - foyer/tests/files/*
    - foyer/tests/implemented_opls_tests.txt

  commands:
    - py.test -v --pyargs foyer

about:
  home: http://mosdef-hub.github.io/foyer
  license: MIT
  summary: Atomtyping and forcefield applying.
